### ISSUE TITLE
Cosmetic error from baseband pipeline

### ISSUE THREAD

**Issue by nmulyk** [CHIMEFRB/workflow#142]
I'm getting the following error when deploying the baseband pipeline on workflow:

Traceback (most recent call last):
  File "/opt/pysetup/.venv/bin/workflow", line 8, in <module>
    sys.exit(cli())
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/chime_frb_api/workflow/cli/pipelines.py", line 72, in deploy
    pipelines: List[str] = [p["id"] for p in response.json()]
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/chime_frb_api/workflow/cli/pipelines.py", line 72, in <listcomp>
    pipelines: List[str] = [p["id"] for p in response.json()]
TypeError: string indices must be integers

The error has been fixed in previous years and reported by Kaitlyn Shin. Thanks!

**Comment by odarotto** [comment]
Hi @nmulyk, can you please provide the YAML file that's being deployed?

**Comment by nmulyk** [comment]
[sample.txt](https://github.com/user-attachments/files/17705441/sample.txt)

**Comment by nmulyk** [comment]
I've copied it to a text file. Please see above. Thanks!

**Comment by odarotto** [comment]
I see @nmulyk, the problem is that you're using the V1 format. Pipelines is now on its version 2 and we have created the `reformat` command so you can easily change your V1 configurations into V2.

Please use `workflow configs reformat <filename>`, this command will reformat your file to be used in version 2.

**Comment by odarotto** [comment]
@nmulyk Yes this needs the last version of workflow. The `workflow.core` package is currently on `v1.11.4`

**Comment by nmulyk** [comment]
Thank you that seems to have worked
